# backend/app/services/filipino_food_db.py
# Curated Filipino food database with average nutritional values per standard serving.
# Sources: DOST-FNRI Philippine Food Composition Tables, verified online nutrition databases.

filipino_foods = [
    # ── Soups / Stews ──────────────────────────────────────────────────────────
    {
        "id": "fil-001",
        "name": "Pork Sinigang",
        "aliases": ["sinigang na baboy", "sinigang", "sinigang baboy"],
        "category": "Soup/Stew",
        "base_serving": "1 bowl (350g)",
        "sodium_mg": 820,
        "calories": 380,
        "saturated_fat_g": 8.2,
        "fiber_g": 3.0,
        "cholesterol_mg": 65,
        "source": "DOST-FNRI",
    },
    {
        "id": "fil-002",
        "name": "Shrimp Sinigang",
        "aliases": ["sinigang na hipon", "sinigang hipon"],
        "category": "Soup/Stew",
        "base_serving": "1 bowl (350g)",
        "sodium_mg": 680,
        "calories": 240,
        "saturated_fat_g": 2.5,
        "fiber_g": 3.0,
        "cholesterol_mg": 150,
        "source": "DOST-FNRI",
    },
    {
        "id": "fil-003",
        "name": "Chicken Tinola",
        "aliases": ["tinolang manok", "tinola"],
        "category": "Soup/Stew",
        "base_serving": "1 bowl (350g)",
        "sodium_mg": 650,
        "calories": 220,
        "saturated_fat_g": 4.0,
        "fiber_g": 2.0,
        "cholesterol_mg": 70,
        "source": "DOST-FNRI",
    },
    {
        "id": "fil-004",
        "name": "Beef Nilaga",
        "aliases": ["nilaga", "nilagang baka", "nilaga baka"],
        "category": "Soup/Stew",
        "base_serving": "1 bowl (350g)",
        "sodium_mg": 750,
        "calories": 320,
        "saturated_fat_g": 7.0,
        "fiber_g": 2.5,
        "cholesterol_mg": 80,
        "source": "DOST-FNRI",
    },
    {
        "id": "fil-005",
        "name": "Bulalo",
        "aliases": ["bulalo soup", "bone marrow soup"],
        "category": "Soup/Stew",
        "base_serving": "1 bowl (400g)",
        "sodium_mg": 880,
        "calories": 450,
        "saturated_fat_g": 12.0,
        "fiber_g": 1.5,
        "cholesterol_mg": 95,
        "source": "DOST-FNRI",
    },
    {
        "id": "fil-006",
        "name": "Monggo Guisado",
        "aliases": ["monggo", "ginisang monggo", "mung bean soup"],
        "category": "Soup/Stew",
        "base_serving": "1 bowl (300g)",
        "sodium_mg": 580,
        "calories": 210,
        "saturated_fat_g": 3.0,
        "fiber_g": 7.0,
        "cholesterol_mg": 20,
        "source": "DOST-FNRI",
    },
    {
        "id": "fil-007",
        "name": "Kare-Kare",
        "aliases": ["kare kare", "oxtail stew"],
        "category": "Soup/Stew",
        "base_serving": "1 bowl (350g)",
        "sodium_mg": 900,
        "calories": 420,
        "saturated_fat_g": 10.0,
        "fiber_g": 3.5,
        "cholesterol_mg": 75,
        "source": "DOST-FNRI",
    },
    {
        "id": "fil-008",
        "name": "Pochero",
        "aliases": ["puchero", "cocido"],
        "category": "Soup/Stew",
        "base_serving": "1 bowl (350g)",
        "sodium_mg": 720,
        "calories": 340,
        "saturated_fat_g": 6.0,
        "fiber_g": 3.0,
        "cholesterol_mg": 60,
        "source": "DOST-FNRI",
    },

    # ── Rice Meals / Ulam ──────────────────────────────────────────────────────
    {
        "id": "fil-009",
        "name": "Pork Adobo",
        "aliases": ["adobong baboy", "adobo baboy", "adobo"],
        "category": "Rice Meal",
        "base_serving": "1 cup (200g)",
        "sodium_mg": 950,
        "calories": 360,
        "saturated_fat_g": 9.5,
        "fiber_g": 0.5,
        "cholesterol_mg": 85,
        "source": "DOST-FNRI",
    },
    {
        "id": "fil-010",
        "name": "Chicken Adobo",
        "aliases": ["adobong manok", "adobo manok"],
        "category": "Rice Meal",
        "base_serving": "1 cup (200g)",
        "sodium_mg": 880,
        "calories": 300,
        "saturated_fat_g": 5.5,
        "fiber_g": 0.5,
        "cholesterol_mg": 90,
        "source": "DOST-FNRI",
    },
    {
        "id": "fil-011",
        "name": "Pork Menudo",
        "aliases": ["menudo", "menudong baboy"],
        "category": "Rice Meal",
        "base_serving": "1 cup (200g)",
        "sodium_mg": 780,
        "calories": 310,
        "saturated_fat_g": 7.0,
        "fiber_g": 2.0,
        "cholesterol_mg": 70,
        "source": "DOST-FNRI",
    },
    {
        "id": "fil-012",
        "name": "Beef Caldereta",
        "aliases": ["caldereta", "kaldereta", "kalderetang baka"],
        "category": "Rice Meal",
        "base_serving": "1 cup (200g)",
        "sodium_mg": 850,
        "calories": 380,
        "saturated_fat_g": 9.0,
        "fiber_g": 2.5,
        "cholesterol_mg": 80,
        "source": "DOST-FNRI",
    },
    {
        "id": "fil-013",
        "name": "Beef Mechado",
        "aliases": ["mechado", "mechadong baka"],
        "category": "Rice Meal",
        "base_serving": "1 cup (200g)",
        "sodium_mg": 800,
        "calories": 340,
        "saturated_fat_g": 8.0,
        "fiber_g": 1.5,
        "cholesterol_mg": 75,
        "source": "DOST-FNRI",
    },
    {
        "id": "fil-014",
        "name": "Pinakbet",
        "aliases": ["pakbet", "pinakbet ilocano"],
        "category": "Rice Meal",
        "base_serving": "1 cup (180g)",
        "sodium_mg": 720,
        "calories": 160,
        "saturated_fat_g": 3.0,
        "fiber_g": 5.0,
        "cholesterol_mg": 15,
        "source": "DOST-FNRI",
    },
    {
        "id": "fil-015",
        "name": "Laing",
        "aliases": ["ginataang laing", "taro leaves in coconut milk"],
        "category": "Rice Meal",
        "base_serving": "1 cup (180g)",
        "sodium_mg": 600,
        "calories": 280,
        "saturated_fat_g": 14.0,
        "fiber_g": 4.0,
        "cholesterol_mg": 10,
        "source": "DOST-FNRI",
    },
    {
        "id": "fil-016",
        "name": "Bicol Express",
        "aliases": ["bicol express", "spicy pork in coconut"],
        "category": "Rice Meal",
        "base_serving": "1 cup (180g)",
        "sodium_mg": 780,
        "calories": 350,
        "saturated_fat_g": 15.0,
        "fiber_g": 2.0,
        "cholesterol_mg": 60,
        "source": "DOST-FNRI",
    },
    {
        "id": "fil-017",
        "name": "Paksiw na Isda",
        "aliases": ["paksiw", "paksiw na bangus", "fish paksiw"],
        "category": "Rice Meal",
        "base_serving": "1 serving (180g)",
        "sodium_mg": 700,
        "calories": 200,
        "saturated_fat_g": 3.0,
        "fiber_g": 1.0,
        "cholesterol_mg": 60,
        "source": "DOST-FNRI",
    },
    {
        "id": "fil-018",
        "name": "Ginataang Kalabasa",
        "aliases": ["ginataang kalabasa", "squash in coconut milk"],
        "category": "Rice Meal",
        "base_serving": "1 cup (200g)",
        "sodium_mg": 480,
        "calories": 220,
        "saturated_fat_g": 10.0,
        "fiber_g": 3.5,
        "cholesterol_mg": 15,
        "source": "DOST-FNRI",
    },
    {
        "id": "fil-019",
        "name": "Bistek Tagalog",
        "aliases": ["bistek", "beef steak tagalog", "bistik"],
        "category": "Rice Meal",
        "base_serving": "1 serving (180g)",
        "sodium_mg": 920,
        "calories": 300,
        "saturated_fat_g": 7.0,
        "fiber_g": 0.5,
        "cholesterol_mg": 70,
        "source": "DOST-FNRI",
    },
    {
        "id": "fil-020",
        "name": "Chicken Afritada",
        "aliases": ["afritada", "afritadang manok"],
        "category": "Rice Meal",
        "base_serving": "1 cup (200g)",
        "sodium_mg": 750,
        "calories": 290,
        "saturated_fat_g": 5.0,
        "fiber_g": 2.0,
        "cholesterol_mg": 75,
        "source": "DOST-FNRI",
    },
    {
        "id": "fil-021",
        "name": "Dinuguan",
        "aliases": ["dinuguan", "pork blood stew", "chocolate meat"],
        "category": "Rice Meal",
        "base_serving": "1 cup (200g)",
        "sodium_mg": 850,
        "calories": 280,
        "saturated_fat_g": 8.0,
        "fiber_g": 0.5,
        "cholesterol_mg": 180,
        "source": "DOST-FNRI",
    },

    # ── Fried Dishes ───────────────────────────────────────────────────────────
    {
        "id": "fil-022",
        "name": "Lechon Kawali",
        "aliases": ["lechon kawali", "crispy pata", "crispy pork belly"],
        "category": "Fried",
        "base_serving": "1 serving (150g)",
        "sodium_mg": 680,
        "calories": 520,
        "saturated_fat_g": 18.0,
        "fiber_g": 0.0,
        "cholesterol_mg": 110,
        "source": "DOST-FNRI",
    },
    {
        "id": "fil-023",
        "name": "Fried Pork Chop",
        "aliases": ["pork chop", "pritong pork chop"],
        "category": "Fried",
        "base_serving": "1 piece (120g)",
        "sodium_mg": 550,
        "calories": 350,
        "saturated_fat_g": 10.0,
        "fiber_g": 0.0,
        "cholesterol_mg": 85,
        "source": "DOST-FNRI",
    },
    {
        "id": "fil-024",
        "name": "Pritong Isda",
        "aliases": ["fried fish", "pritong galunggong", "fried galunggong"],
        "category": "Fried",
        "base_serving": "1 piece (120g)",
        "sodium_mg": 420,
        "calories": 280,
        "saturated_fat_g": 5.0,
        "fiber_g": 0.0,
        "cholesterol_mg": 70,
        "source": "DOST-FNRI",
    },
    {
        "id": "fil-025",
        "name": "Lumpiang Shanghai",
        "aliases": ["lumpia", "lumpiang shanghai", "spring rolls"],
        "category": "Fried",
        "base_serving": "5 pieces (100g)",
        "sodium_mg": 620,
        "calories": 330,
        "saturated_fat_g": 7.0,
        "fiber_g": 1.0,
        "cholesterol_mg": 50,
        "source": "DOST-FNRI",
    },
    {
        "id": "fil-026",
        "name": "Kwek-Kwek",
        "aliases": ["kwek kwek", "tokneneng", "fried quail eggs"],
        "category": "Fried",
        "base_serving": "6 pieces (120g)",
        "sodium_mg": 480,
        "calories": 290,
        "saturated_fat_g": 6.0,
        "fiber_g": 0.5,
        "cholesterol_mg": 320,
        "source": "DOST-FNRI",
    },
    {
        "id": "fil-027",
        "name": "Tokwa't Baboy",
        "aliases": ["tokwat baboy", "tofu and pork"],
        "category": "Fried",
        "base_serving": "1 plate (200g)",
        "sodium_mg": 850,
        "calories": 310,
        "saturated_fat_g": 7.0,
        "fiber_g": 1.5,
        "cholesterol_mg": 55,
        "source": "DOST-FNRI",
    },

    # ── Grilled ────────────────────────────────────────────────────────────────
    {
        "id": "fil-028",
        "name": "Inihaw na Bangus",
        "aliases": ["grilled bangus", "grilled milkfish", "inihaw bangus"],
        "category": "Grilled",
        "base_serving": "1 fillet (180g)",
        "sodium_mg": 380,
        "calories": 280,
        "saturated_fat_g": 4.0,
        "fiber_g": 0.0,
        "cholesterol_mg": 65,
        "source": "DOST-FNRI",
    },
    {
        "id": "fil-029",
        "name": "Inihaw na Liempo",
        "aliases": ["grilled liempo", "grilled pork belly", "inihaw liempo"],
        "category": "Grilled",
        "base_serving": "1 serving (150g)",
        "sodium_mg": 580,
        "calories": 420,
        "saturated_fat_g": 14.0,
        "fiber_g": 0.0,
        "cholesterol_mg": 90,
        "source": "DOST-FNRI",
    },
    {
        "id": "fil-030",
        "name": "Chicken BBQ",
        "aliases": ["chicken barbecue", "chicken bbq", "bbq manok", "chicken inasal"],
        "category": "Grilled",
        "base_serving": "1 stick (100g)",
        "sodium_mg": 520,
        "calories": 220,
        "saturated_fat_g": 4.0,
        "fiber_g": 0.0,
        "cholesterol_mg": 80,
        "source": "DOST-FNRI",
    },
    {
        "id": "fil-031",
        "name": "Isaw",
        "aliases": ["isaw", "grilled intestine", "chicken intestine"],
        "category": "Grilled",
        "base_serving": "3 sticks (90g)",
        "sodium_mg": 450,
        "calories": 180,
        "saturated_fat_g": 5.0,
        "fiber_g": 0.0,
        "cholesterol_mg": 120,
        "source": "DOST-FNRI",
    },

    # ── Breakfast / Silog ──────────────────────────────────────────────────────
    {
        "id": "fil-032",
        "name": "Tapsilog",
        "aliases": ["tapsilog", "tapa silog", "beef tapa with rice"],
        "category": "Breakfast",
        "base_serving": "1 plate (300g)",
        "sodium_mg": 1050,
        "calories": 550,
        "saturated_fat_g": 10.0,
        "fiber_g": 0.5,
        "cholesterol_mg": 90,
        "source": "DOST-FNRI",
    },
    {
        "id": "fil-033",
        "name": "Longsilog",
        "aliases": ["longsilog", "longganisa silog", "longganisa with rice"],
        "category": "Breakfast",
        "base_serving": "1 plate (300g)",
        "sodium_mg": 1100,
        "calories": 580,
        "saturated_fat_g": 14.0,
        "fiber_g": 0.5,
        "cholesterol_mg": 100,
        "source": "DOST-FNRI",
    },
    {
        "id": "fil-034",
        "name": "Tocilog",
        "aliases": ["tocilog", "tocino silog", "tocino with rice"],
        "category": "Breakfast",
        "base_serving": "1 plate (300g)",
        "sodium_mg": 980,
        "calories": 560,
        "saturated_fat_g": 12.0,
        "fiber_g": 0.5,
        "cholesterol_mg": 85,
        "source": "DOST-FNRI",
    },
    {
        "id": "fil-035",
        "name": "Cornsilog",
        "aliases": ["cornsilog", "corned beef silog"],
        "category": "Breakfast",
        "base_serving": "1 plate (280g)",
        "sodium_mg": 1200,
        "calories": 520,
        "saturated_fat_g": 11.0,
        "fiber_g": 0.5,
        "cholesterol_mg": 70,
        "source": "DOST-FNRI",
    },
    {
        "id": "fil-036",
        "name": "Champorado",
        "aliases": ["champorado", "chocolate rice porridge"],
        "category": "Breakfast",
        "base_serving": "1 bowl (250g)",
        "sodium_mg": 60,
        "calories": 280,
        "saturated_fat_g": 3.0,
        "fiber_g": 2.0,
        "cholesterol_mg": 5,
        "source": "DOST-FNRI",
    },
    {
        "id": "fil-037",
        "name": "Pandesal",
        "aliases": ["pandesal", "pan de sal", "bread roll"],
        "category": "Breakfast",
        "base_serving": "2 pieces (60g)",
        "sodium_mg": 280,
        "calories": 180,
        "saturated_fat_g": 1.5,
        "fiber_g": 1.0,
        "cholesterol_mg": 5,
        "source": "DOST-FNRI",
    },
    {
        "id": "fil-038",
        "name": "Lugaw / Arroz Caldo",
        "aliases": ["lugaw", "arroz caldo", "goto", "rice porridge"],
        "category": "Breakfast",
        "base_serving": "1 bowl (300g)",
        "sodium_mg": 680,
        "calories": 250,
        "saturated_fat_g": 3.5,
        "fiber_g": 0.5,
        "cholesterol_mg": 30,
        "source": "DOST-FNRI",
    },
    {
        "id": "fil-039",
        "name": "Tortang Talong",
        "aliases": ["tortang talong", "eggplant omelette"],
        "category": "Breakfast",
        "base_serving": "1 piece (150g)",
        "sodium_mg": 420,
        "calories": 220,
        "saturated_fat_g": 4.0,
        "fiber_g": 3.0,
        "cholesterol_mg": 190,
        "source": "DOST-FNRI",
    },

    # ── Snacks / Street Food ───────────────────────────────────────────────────
    {
        "id": "fil-040",
        "name": "Fish Ball with Sauce",
        "aliases": ["fishball", "fish ball", "fish balls"],
        "category": "Snack",
        "base_serving": "10 pieces (120g)",
        "sodium_mg": 680,
        "calories": 200,
        "saturated_fat_g": 4.0,
        "fiber_g": 0.0,
        "cholesterol_mg": 35,
        "source": "DOST-FNRI",
    },
    {
        "id": "fil-041",
        "name": "Banana Cue",
        "aliases": ["banana cue", "bananacue", "banana q"],
        "category": "Snack",
        "base_serving": "2 pieces (150g)",
        "sodium_mg": 10,
        "calories": 320,
        "saturated_fat_g": 5.0,
        "fiber_g": 3.0,
        "cholesterol_mg": 0,
        "source": "DOST-FNRI",
    },
    {
        "id": "fil-042",
        "name": "Turon",
        "aliases": ["turon", "banana lumpia", "fried banana roll"],
        "category": "Snack",
        "base_serving": "2 pieces (120g)",
        "sodium_mg": 30,
        "calories": 310,
        "saturated_fat_g": 4.5,
        "fiber_g": 2.0,
        "cholesterol_mg": 0,
        "source": "DOST-FNRI",
    },
    {
        "id": "fil-043",
        "name": "Halo-Halo",
        "aliases": ["halo halo", "haluhalo", "halo-halo"],
        "category": "Snack",
        "base_serving": "1 glass (350g)",
        "sodium_mg": 80,
        "calories": 380,
        "saturated_fat_g": 6.0,
        "fiber_g": 2.5,
        "cholesterol_mg": 20,
        "source": "DOST-FNRI",
    },
    {
        "id": "fil-044",
        "name": "Bibingka",
        "aliases": ["bibingka", "rice cake"],
        "category": "Snack",
        "base_serving": "1 piece (100g)",
        "sodium_mg": 220,
        "calories": 260,
        "saturated_fat_g": 5.0,
        "fiber_g": 0.5,
        "cholesterol_mg": 40,
        "source": "DOST-FNRI",
    },
    {
        "id": "fil-045",
        "name": "Puto",
        "aliases": ["puto", "steamed rice cake"],
        "category": "Snack",
        "base_serving": "3 pieces (90g)",
        "sodium_mg": 200,
        "calories": 210,
        "saturated_fat_g": 2.0,
        "fiber_g": 0.5,
        "cholesterol_mg": 15,
        "source": "DOST-FNRI",
    },

    # ── Vegetables / Sides ─────────────────────────────────────────────────────
    {
        "id": "fil-046",
        "name": "Ensaladang Talong",
        "aliases": ["eggplant salad", "grilled eggplant salad"],
        "category": "Vegetable",
        "base_serving": "1 plate (180g)",
        "sodium_mg": 350,
        "calories": 90,
        "saturated_fat_g": 0.5,
        "fiber_g": 5.0,
        "cholesterol_mg": 0,
        "source": "DOST-FNRI",
    },
    {
        "id": "fil-047",
        "name": "Ginisang Ampalaya",
        "aliases": ["ampalaya", "bitter gourd", "ginisang ampalaya", "bitter melon"],
        "category": "Vegetable",
        "base_serving": "1 cup (160g)",
        "sodium_mg": 480,
        "calories": 120,
        "saturated_fat_g": 2.0,
        "fiber_g": 4.0,
        "cholesterol_mg": 45,
        "source": "DOST-FNRI",
    },
    {
        "id": "fil-048",
        "name": "Chopsuey",
        "aliases": ["chopsuey", "chop suey", "mixed vegetables"],
        "category": "Vegetable",
        "base_serving": "1 cup (200g)",
        "sodium_mg": 650,
        "calories": 180,
        "saturated_fat_g": 3.0,
        "fiber_g": 4.5,
        "cholesterol_mg": 25,
        "source": "DOST-FNRI",
    },
    {
        "id": "fil-049",
        "name": "Pancit Canton",
        "aliases": ["pancit", "pansit canton", "pancit guisado", "pansit"],
        "category": "Side",
        "base_serving": "1 plate (250g)",
        "sodium_mg": 920,
        "calories": 380,
        "saturated_fat_g": 5.0,
        "fiber_g": 2.0,
        "cholesterol_mg": 40,
        "source": "DOST-FNRI",
    },
    {
        "id": "fil-050",
        "name": "Pancit Bihon",
        "aliases": ["pansit bihon", "bihon guisado", "rice noodles"],
        "category": "Side",
        "base_serving": "1 plate (250g)",
        "sodium_mg": 780,
        "calories": 340,
        "saturated_fat_g": 3.5,
        "fiber_g": 2.0,
        "cholesterol_mg": 30,
        "source": "DOST-FNRI",
    },

    # ── Beverages ──────────────────────────────────────────────────────────────
    {
        "id": "fil-051",
        "name": "Sago't Gulaman",
        "aliases": ["sago gulaman", "sago at gulaman"],
        "category": "Beverage",
        "base_serving": "1 glass (350ml)",
        "sodium_mg": 30,
        "calories": 220,
        "saturated_fat_g": 0.0,
        "fiber_g": 1.0,
        "cholesterol_mg": 0,
        "source": "DOST-FNRI",
    },
    {
        "id": "fil-052",
        "name": "Buko Juice",
        "aliases": ["buko juice", "coconut juice", "coconut water", "buko"],
        "category": "Beverage",
        "base_serving": "1 glass (250ml)",
        "sodium_mg": 50,
        "calories": 45,
        "saturated_fat_g": 0.0,
        "fiber_g": 0.0,
        "cholesterol_mg": 0,
        "source": "DOST-FNRI",
    },

    # ── Extras (common add-ons) ────────────────────────────────────────────────
    {
        "id": "fil-053",
        "name": "Plain White Rice",
        "aliases": ["kanin", "rice", "steamed rice", "white rice"],
        "category": "Side",
        "base_serving": "1 cup (200g)",
        "sodium_mg": 5,
        "calories": 240,
        "saturated_fat_g": 0.1,
        "fiber_g": 0.5,
        "cholesterol_mg": 0,
        "source": "DOST-FNRI",
    },
    {
        "id": "fil-054",
        "name": "Fried Rice (Sinangag)",
        "aliases": ["sinangag", "garlic rice", "fried rice"],
        "category": "Side",
        "base_serving": "1 cup (200g)",
        "sodium_mg": 320,
        "calories": 310,
        "saturated_fat_g": 3.0,
        "fiber_g": 0.5,
        "cholesterol_mg": 10,
        "source": "DOST-FNRI",
    },
    {
        "id": "fil-055",
        "name": "Fried Egg",
        "aliases": ["pritong itlog", "fried egg", "egg"],
        "category": "Side",
        "base_serving": "1 piece (50g)",
        "sodium_mg": 170,
        "calories": 90,
        "saturated_fat_g": 2.0,
        "fiber_g": 0.0,
        "cholesterol_mg": 185,
        "source": "DOST-FNRI",
    },
]


def search_filipino_foods(query: str, limit: int = 5):
    """
    Fuzzy-match query against name and aliases. Returns top matches.
    """
    if not query or not query.strip():
        return []

    q = query.lower().strip()
    scored = []

    for food in filipino_foods:
        name_lower = food["name"].lower()
        # Exact name match gets highest priority
        if q == name_lower:
            scored.append((food, 100))
            continue

        # Name starts with query
        if name_lower.startswith(q):
            scored.append((food, 80))
            continue

        # Name contains query
        if q in name_lower:
            scored.append((food, 60))
            continue

        # Check aliases
        alias_match = False
        for alias in food.get("aliases", []):
            alias_lower = alias.lower()
            if q == alias_lower:
                scored.append((food, 90))
                alias_match = True
                break
            elif alias_lower.startswith(q):
                scored.append((food, 70))
                alias_match = True
                break
            elif q in alias_lower:
                scored.append((food, 50))
                alias_match = True
                break

        if not alias_match:
            # Check if any word in query matches any word in name
            q_words = q.split()
            name_words = name_lower.split()
            for qw in q_words:
                if any(qw in nw for nw in name_words):
                    scored.append((food, 30))
                    break

    scored.sort(key=lambda x: x[1], reverse=True)
    return [item[0] for item in scored[:limit]]
