import React, { useState, useEffect } from "react";
import { X, Activity, AlertTriangle, Ban, CheckCircle2, Archive, Key, Copy } from "lucide-react";

const PatientDetailsModal = ({ isOpen, onClose, patient, onDeactivate, onEnable }) => {
  const [tempPassword, setTempPassword] = useState("");

  useEffect(() => {
    if (!isOpen) {
      setTempPassword("");
    }
  }, [isOpen]);

  if (!isOpen || !patient) return null;

  const getStatusBadge = (status) => {
    if (status === "Active")
      return (
        <span className="bg-emerald-50 text-emerald-700 border border-emerald-200 px-2 py-0.5 rounded-full text-[9px] font-bold uppercase tracking-[0.15em] flex items-center gap-1 w-fit">
          <CheckCircle2 size={10} /> Active
        </span>
      );
    if (status === "Disabled")
      return (
        <span className="bg-red-50 text-red-700 border border-red-200 px-2 py-0.5 rounded-full text-[9px] font-bold uppercase tracking-[0.15em] flex items-center gap-1 w-fit">
          <Ban size={10} /> Disabled
        </span>
      );
    return (
      <span className="bg-slate-50 text-slate-500 border border-slate-200 px-2 py-0.5 rounded-full text-[9px] font-bold uppercase tracking-[0.15em] flex items-center gap-1 w-fit">
        <Archive size={10} /> Archived
      </span>
    );
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6">
      <div
        className="absolute inset-0 bg-slate-900/40 backdrop-blur-sm transition-opacity"
        onClick={onClose}
      ></div>

      <div className="relative w-full max-w-lg bg-slate-50 max-h-full rounded-2xl shadow-2xl flex flex-col animate-in fade-in zoom-in-95 duration-200 overflow-hidden">
        {/* Modal Header */}
        <div className="flex items-center justify-between px-6 py-5 border-b border-slate-200 bg-white shadow-sm z-10">
          <div>
            <h3 className="text-base font-semibold text-slate-900">User Details</h3>
            <p className="text-[11px] text-slate-500 mt-1">{patient.name}</p>
          </div>
          <button
            onClick={onClose}
            className="text-slate-400 hover:text-slate-900 p-2 rounded-xl hover:bg-slate-100 transition-colors"
          >
            <X size={18} />
          </button>
        </div>

        {/* Modal Content Area */}
        <div className="flex-1 overflow-y-auto p-6 custom-scrollbar space-y-6">
          {/* Identity Card */}
          <div className="bg-white p-5 rounded-2xl border border-slate-200 shadow-sm flex items-center justify-between">
            <div>
              <h2 className="text-xl font-bold text-slate-900">{patient.name}</h2>
              <p className="text-xs text-slate-500 font-mono mt-1">{patient.id}</p>
            </div>
            {getStatusBadge(patient.status)}
          </div>

          {/* Engagement Data */}
          <div>
            <h4 className="text-[10px] font-semibold text-slate-400 uppercase tracking-[0.2em] border-b border-slate-100 pb-2 mb-4 flex items-center gap-2">
              <Activity size={13} /> Engagement Metrics
            </h4>
            <div className="grid grid-cols-2 gap-4">
              <div className="bg-white p-4 rounded-xl border border-slate-200 shadow-sm">
                <p className="text-[10px] font-medium text-slate-500 uppercase tracking-widest mb-1.5">
                  Logins (7 Days)
                </p>
                <p className="text-2xl font-bold text-slate-900">
                  {patient.metrics?.loginsThisWeek}
                </p>
              </div>
              <div className="bg-white p-4 rounded-xl border border-slate-200 shadow-sm">
                <p className="text-[10px] font-medium text-slate-500 uppercase tracking-widest mb-1.5">
                  Avg Session
                </p>
                <p className="text-2xl font-bold text-slate-900">
                  {patient.metrics?.avgSession}
                </p>
              </div>
            </div>
          </div>

          {/* Alert Frequency */}
          <div>
            <h4 className="text-[10px] font-semibold text-red-500 uppercase tracking-[0.2em] border-b border-red-100 pb-2 mb-4 flex items-center gap-2">
              <AlertTriangle size={13} /> Alert History
            </h4>
            <div className="bg-red-50 p-5 rounded-xl border border-red-100 flex items-center justify-between">
              <div>
                <p className="text-[10px] font-bold text-red-800 uppercase tracking-widest mb-1">
                  High-Risk Triggers
                </p>
                <p className="text-xs text-red-600/80 font-medium">
                  Total alerts generated by this account.
                </p>
              </div>
              <span className="text-3xl font-bold text-red-600">
                {patient.metrics?.alertsTriggered}
              </span>
            </div>
          </div>

          {/* Disabled Context (if applicable) */}
          {patient.status === "Disabled" && (
            <div className="bg-slate-100 border border-slate-200 p-5 rounded-xl">
              <p className="text-[10px] font-bold text-slate-600 uppercase tracking-widest mb-2 flex items-center gap-1.5">
                <Ban size={12} /> Deactivation Log
              </p>
              <p className="text-xs font-medium text-slate-800 italic leading-relaxed">
                "{patient.deactivationReason}"
              </p>
            </div>
          )}
        </div>

        {/* Modal Footer Actions */}
        <div className="px-6 py-4 border-t border-slate-200 bg-slate-50 flex flex-wrap sm:flex-nowrap justify-between items-center gap-4 shrink-0 w-full">
          {patient.status === "Disabled" ? (
            <button
              onClick={onEnable}
              className="flex items-center gap-2 px-5 py-2.5 text-xs font-semibold text-white bg-emerald-600 hover:bg-emerald-700 rounded-xl shadow-sm transition-colors"
            >
              <CheckCircle2 size={14} /> Re-enable Account
            </button>
          ) : patient.status === "Active" ? (
            <button
              onClick={onDeactivate}
              className="flex items-center gap-2 px-5 py-2.5 text-xs font-semibold text-white bg-red-600 hover:bg-red-700 rounded-xl shadow-sm transition-colors"
            >
              <Ban size={14} /> Disable Account
            </button>
          ) : (
            <div />
          )}

          <div className="flex flex-wrap sm:flex-nowrap items-center gap-3 relative w-full sm:w-auto justify-end">
            {tempPassword && (
              <div className="absolute bottom-full mb-3 right-0 bg-yellow-50 border border-yellow-200 text-yellow-800 px-4 py-2.5 rounded-xl text-xs font-semibold shadow-sm flex items-center gap-3 animate-in fade-in slide-in-from-bottom-2 whitespace-nowrap">
                <span>New Temporary Password: <span className="font-mono bg-white px-2 py-0.5 rounded border border-yellow-300 ml-1 select-all">{tempPassword}</span></span>
                <button
                  onClick={() => navigator.clipboard.writeText(tempPassword)}
                  className="text-yellow-600 hover:text-yellow-800 transition-colors p-1 hover:bg-yellow-100 rounded-md"
                  title="Copy to clipboard"
                >
                  <Copy size={14} />
                </button>
              </div>
            )}
            <button
              onClick={() => {
                const otp = Math.floor(100000 + Math.random() * 900000).toString();
                setTempPassword(otp);
              }}
              className="flex items-center justify-center gap-2 px-4 py-2.5 text-xs font-semibold text-slate-700 bg-white border border-slate-200 hover:bg-slate-100 rounded-xl transition-colors shadow-sm whitespace-nowrap w-full sm:w-auto"
            >
              <Key size={14} /> Generate OTP
            </button>
            <button
              onClick={onClose}
              className="px-6 py-2.5 text-xs font-semibold text-slate-700 bg-slate-100 border border-slate-200 hover:bg-slate-200 rounded-xl transition-colors shadow-sm w-full sm:w-auto"
            >
              Close
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default PatientDetailsModal;
