/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        'background': 'rgb(var(--color-background) / <alpha-value>)',
        'surface': 'rgb(var(--color-surface) / <alpha-value>)',
        'surface-alt': 'rgb(var(--color-surface-alt) / <alpha-value>)',
        'border': 'rgb(var(--color-border) / <alpha-value>)',
        'border-strong': 'rgb(var(--color-border-strong) / <alpha-value>)',
        'text': 'rgb(var(--color-text) / <alpha-value>)',
        'text-soft': 'rgb(var(--color-text-soft) / <alpha-value>)',
        'text-muted': 'rgb(var(--color-text-muted) / <alpha-value>)',
        'disabled-fill': 'rgb(var(--color-disabled-fill) / <alpha-value>)',
        'disabled-text': 'rgb(var(--color-disabled-text) / <alpha-value>)',
        'ink': 'rgb(var(--color-ink) / <alpha-value>)',
        'on-ink': 'rgb(var(--color-on-ink) / <alpha-value>)',
        'focus-ring': 'rgb(var(--color-focus-ring) / <alpha-value>)',
        'primary': 'rgb(var(--color-primary) / <alpha-value>)',
        'primary-pressed': 'rgb(var(--color-primary-pressed) / <alpha-value>)',
        'on-primary': 'rgb(var(--color-on-primary) / <alpha-value>)',
        'blue': 'rgb(var(--color-blue) / <alpha-value>)',
        'blue-mid': 'rgb(var(--color-blue-mid) / <alpha-value>)',
        'blue-text': 'rgb(var(--color-blue-text) / <alpha-value>)',
        'blue-tint': 'rgb(var(--color-blue-tint) / <alpha-value>)',
        'sky': 'rgb(var(--color-sky) / <alpha-value>)',
        'sky-mid': 'rgb(var(--color-sky-mid) / <alpha-value>)',
        'sky-text': 'rgb(var(--color-sky-text) / <alpha-value>)',
        'sky-tint': 'rgb(var(--color-sky-tint) / <alpha-value>)',
        'teal': 'rgb(var(--color-teal) / <alpha-value>)',
        'teal-mid': 'rgb(var(--color-teal-mid) / <alpha-value>)',
        'teal-text': 'rgb(var(--color-teal-text) / <alpha-value>)',
        'teal-tint': 'rgb(var(--color-teal-tint) / <alpha-value>)',
        'lime': 'rgb(var(--color-lime) / <alpha-value>)',
        'lime-mid': 'rgb(var(--color-lime-mid) / <alpha-value>)',
        'lime-text': 'rgb(var(--color-lime-text) / <alpha-value>)',
        'lime-tint': 'rgb(var(--color-lime-tint) / <alpha-value>)',
        'success': 'rgb(var(--color-success) / <alpha-value>)',
        'success-mid': 'rgb(var(--color-success-mid) / <alpha-value>)',
        'success-text': 'rgb(var(--color-success-text) / <alpha-value>)',
        'success-tint': 'rgb(var(--color-success-tint) / <alpha-value>)',
        'warning': 'rgb(var(--color-warning) / <alpha-value>)',
        'warning-mid': 'rgb(var(--color-warning-mid) / <alpha-value>)',
        'warning-text': 'rgb(var(--color-warning-text) / <alpha-value>)',
        'warning-tint': 'rgb(var(--color-warning-tint) / <alpha-value>)',
        'danger': 'rgb(var(--color-danger) / <alpha-value>)',
        'danger-mid': 'rgb(var(--color-danger-mid) / <alpha-value>)',
        'danger-text': 'rgb(var(--color-danger-text) / <alpha-value>)',
        'danger-tint': 'rgb(var(--color-danger-tint) / <alpha-value>)',
        'success-solid': 'rgb(var(--color-success-solid) / <alpha-value>)',
        'on-success': 'rgb(var(--color-on-success) / <alpha-value>)',
        'danger-solid': 'rgb(var(--color-danger-solid) / <alpha-value>)',
        'on-danger': 'rgb(var(--color-on-danger) / <alpha-value>)',
        'warning-solid': 'rgb(var(--color-warning-solid) / <alpha-value>)',
        'on-warning': 'rgb(var(--color-on-warning) / <alpha-value>)',
      },
    },
  },
  plugins: [],
};